import type { IconType } from "react-icons";
import {
  SiAdobeacrobatreader,
  SiAdobeillustrator,
  SiAdobelightroom,
  SiAdobephotoshop,
  SiApache,
  SiAxios,
  SiBehance,
  SiBootstrap,
  SiExpress,
  SiFigma,
  SiFramer,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiJavascript,
  SiJsonwebtokens,
  SiLaravel,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiNpm,
  SiPhp,
  SiPostgresql,
  SiReact,
  SiReactrouter,
  SiSequelize,
  SiSupabase,
  SiSvelte,
  SiTailwindcss,
  SiTypescript,
  SiUbuntu,
  SiVercel,
  SiVite,
} from "react-icons/si";
import type { Project, ProjectLink, TechIcon } from "@/lib/types";

const tech = (
  id: string,
  label: string,
  icon: IconType,
  color: string,
  darkColor?: string,
): TechIcon => ({
  id,
  icon,
  color,
  ...(darkColor ? { darkColor } : {}),
  label,
});

const projectLink = (
  id: string,
  label: string,
  href: string,
  variant: ProjectLink["variant"],
): ProjectLink => ({
  id,
  label,
  href,
  variant,
});

export const projects: Project[] = [
  {
    id: "project-management-system",
    title: "Project Management System",
    role: "Fullstack Developer",
    type: "Enterprise project management system",
    description:
      "A robust enterprise resource and project management system built to streamline business operations. Features include comprehensive modules for managing projects, partners (Mitras), financial records, certificates, and daily activities with file attachment support. The platform ensures secure data handling through JWT authentication and role-based access control (RBAC), complemented by an interactive dashboard for seamless monitoring.",
    impact:
      "Delivered an integrated operational platform for project, partner, finance, certificate, and activity workflows with secure role-based access.",
    highlights: [
      "Built backend modules and REST API flows with Laravel.",
      "Implemented responsive SvelteKit interfaces for operational teams.",
      "Connected authentication, permissions, files, and dashboard monitoring.",
    ],
    featured: true,
    year: "2025",
    status: "Production work",
    tech: [
      tech("sveltekit", "SvelteKit", SiSvelte, "#FF3E00"),
      tech("tailwindcss", "Tailwind CSS", SiTailwindcss, "#06B6D4"),
      tech("vite", "Vite", SiVite, "#646CFF"),
      tech("typescript", "TypeScript", SiTypescript, "#3178C6"),
      tech("php", "PHP", SiPhp, "#777BB4"),
      tech("laravel", "Laravel", SiLaravel, "#FF2D20"),
      tech("mysql", "MySQL", SiMysql, "#4479A1"),
      tech("jwt-auth", "JWT Auth", SiJsonwebtokens, "#000000", "#ffffff"),
      tech("axios", "Axios", SiAxios, "#5A29E4"),
      tech("bootstrap", "Bootstrap", SiBootstrap, "#7952B3"),
      tech("npm", "NPM", SiNpm, "#CB3837"),
      tech("apache", "Apache", SiApache, "#D62D20"),
      tech("mongodb", "MongoDB", SiMongodb, "#47A248"),
      tech("git", "Git", SiGit, "#F05032"),
      tech("github", "GitHub", SiGithub, "#181717", "#e6edf3"),
      tech("github-actions", "GitHub Actions", SiGithubactions, "#2088FF"),
      tech("linux", "Linux", SiLinux, "#FCC624"),
      tech("ubuntu", "Ubuntu", SiUbuntu, "#E95420"),
    ],
    links: [
      projectLink(
        "frontend",
        "Frontend",
        "https://github.com/indogreen/project-management",
        "primary",
      ),
      projectLink(
        "backend",
        "Backend",
        "https://github.com/indogreen/project-management",
        "secondary",
      ),
    ],
    thumbnail: "/projects/project-management.png",
    bgColor: "#262626",
  },
  {
    id: "my-portfolio",
    title: "My Portfolio",
    role: "Designer and Frontend Developer",
    type: "Personal brand and recruiter portfolio",
    description:
      "A modern, responsive personal portfolio website crafted to showcase projects, skills, and professional background. Built with Next.js 16 and React 19 on a TypeScript foundation, the site features a sleek dark/light theme system powered by next-themes, fluid page animations using Framer Motion, and a fully responsive layout styled with Tailwind CSS v4. Key highlights include an animated typing hero section, an interactive project gallery with detail modals, a categorized skills showcase, and a functional contact form.",
    impact:
      "Created a fast, polished portfolio that turns work history, project proof, and contact paths into a recruiter-friendly single-page experience.",
    highlights: [
      "Built with Next.js App Router, React, TypeScript, and Tailwind CSS.",
      "Added dark/light theme support, motion, project detail modals, and contact flow.",
      "Structured content so recruiters can scan role fit, stack, and proof quickly.",
    ],
    featured: true,
    year: "2026",
    status: "Live",
    tech: [
      tech("nextjs", "Next.js", SiNextdotjs, "#000000", "#ffffff"),
      tech("react", "React", SiReact, "#61DAFB"),
      tech("typescript", "TypeScript", SiTypescript, "#3178C6"),
      tech("tailwindcss", "Tailwind CSS", SiTailwindcss, "#06B6D4"),
      tech("framer-motion", "Framer Motion", SiFramer, "#0055FF"),
      tech("npm", "NPM", SiNpm, "#CB3837"),
      tech("git", "Git", SiGit, "#F05032"),
      tech("github", "GitHub", SiGithub, "#181717", "#e6edf3"),
      tech("github-actions", "GitHub Actions", SiGithubactions, "#2088FF"),
      tech("vercel", "Vercel", SiVercel, "#000000", "#ffffff"),
    ],
    links: [
      projectLink(
        "live-demo",
        "Live Demo",
        "https://kupzed.vercel.app",
        "primary",
      ),
      projectLink(
        "source-code",
        "Source Code",
        "https://github.com/kupzed/my-portfolio",
        "secondary",
      ),
    ],
    thumbnail: "/projects/my-portfolio.png",
    bgColor: "#4dad84",
  },
  {
    id: "catatz",
    title: "CatatZ",
    role: "Fullstack Developer",
    type: "Personal finance tracking PWA",
    description:
      "A fullstack personal finance tracking application built to help users manage income, expenses, transfers, balance corrections, accounts, categories, debts, receivables, and financial recaps. The app uses Supabase Auth and PostgreSQL for secure user data, supports PDF report export, and includes a PWA experience with install prompts, offline shell, update prompts, and offline transaction queueing.",
    impact:
      "Built a production-ready finance workflow with authentication, PostgreSQL-backed data, financial reports, and offline-friendly mobile behavior.",
    highlights: [
      "Implemented transaction, account, category, debt, receivable, and recap flows.",
      "Integrated Supabase Auth, PostgreSQL, protected data access, and deployment config.",
      "Added PWA install behavior, offline shell, update prompts, and transaction queueing.",
    ],
    featured: true,
    year: "2026",
    status: "Live",
    tech: [
      tech("nextjs", "Next.js", SiNextdotjs, "#000000", "#ffffff"),
      tech("react", "React", SiReact, "#61DAFB"),
      tech("typescript", "TypeScript", SiTypescript, "#3178C6"),
      tech("tailwindcss", "Tailwind CSS", SiTailwindcss, "#06B6D4"),
      tech("supabase", "Supabase", SiSupabase, "#3ECF8E"),
      tech("postgresql", "PostgreSQL", SiPostgresql, "#4169E1"),
      tech("vercel", "Vercel", SiVercel, "#000000", "#ffffff"),
      tech("npm", "NPM", SiNpm, "#CB3837"),
      tech("git", "Git", SiGit, "#F05032"),
      tech("github", "GitHub", SiGithub, "#181717", "#e6edf3"),
    ],
    links: [
      projectLink(
        "live-demo",
        "Live Demo",
        "https://catatz.vercel.app",
        "primary",
      ),
      projectLink(
        "source-code",
        "Source Code",
        "https://github.com/kupzed/catatz",
        "secondary",
      ),
    ],
    thumbnail: "/projects/catatz.png",
    bgColor: "#0052FF",
  },
  {
    id: "project-management-system-v2",
    title: "Project Management System V2",
    role: "Frontend Developer",
    type: "Enterprise UI modernization",
    description:
      "The second iteration of the enterprise management platform, featuring a completely overhauled, highly responsive user interface. This version focuses on a superior user experience by introducing dark mode support, a more intuitive modern layout, and advanced data filtering systems optimized separately for mobile and desktop views. It seamlessly connects to the existing secure backend to manage projects, financial records, partners, and certificates with improved speed and accessibility.",
    impact:
      "Modernized the operational interface with faster scanning, stronger responsive behavior, dark mode, and filtering patterns for field and desktop users.",
    highlights: [
      "Rebuilt the frontend experience with SvelteKit, TypeScript, and Tailwind CSS.",
      "Designed mobile and desktop filtering patterns for operational data.",
      "Connected the new interface to the existing secure Laravel backend.",
    ],
    year: "2026",
    status: "Production work",
    tech: [
      tech("sveltekit", "SvelteKit", SiSvelte, "#FF3E00"),
      tech("tailwindcss", "Tailwind CSS", SiTailwindcss, "#06B6D4"),
      tech("vite", "Vite", SiVite, "#646CFF"),
      tech("typescript", "TypeScript", SiTypescript, "#3178C6"),
      tech("php", "PHP", SiPhp, "#777BB4"),
      tech("laravel", "Laravel", SiLaravel, "#FF2D20"),
      tech("mysql", "MySQL", SiMysql, "#4479A1"),
      tech("jwt-auth", "JWT Auth", SiJsonwebtokens, "#000000", "#ffffff"),
      tech("bootstrap", "Bootstrap", SiBootstrap, "#7952B3"),
      tech("npm", "NPM", SiNpm, "#CB3837"),
      tech("apache", "Apache", SiApache, "#D62D20"),
      tech("mongodb", "MongoDB", SiMongodb, "#47A248"),
      tech("git", "Git", SiGit, "#F05032"),
      tech("github", "GitHub", SiGithub, "#181717", "#e6edf3"),
      tech("github-actions", "GitHub Actions", SiGithubactions, "#2088FF"),
      tech("linux", "Linux", SiLinux, "#FCC624"),
      tech("ubuntu", "Ubuntu", SiUbuntu, "#E95420"),
    ],
    links: [
      projectLink(
        "frontend",
        "Frontend",
        "https://github.com/indogreen/project-management",
        "primary",
      ),
      projectLink(
        "backend",
        "Backend",
        "https://github.com/indogreen/project-management",
        "secondary",
      ),
    ],
    thumbnail: "/projects/project-management-v2.png",
    bgColor: "#23183b",
  },
  {
    id: "inner-strength",
    title: "Inner Strength",
    role: "Frontend Developer and UI Contributor",
    type: "Mental health platform prototype",
    description:
      "Sebuah platform kesehatan mental komprehensif yang dirancang untuk membantu pengguna mengelola kondisi psikologis seperti Anxiety, Bipolar, dan Depresi. Fitur utama mencakup sistem konsultasi online/offline dengan terapis profesional, komunitas berbagi antar pengguna, konten edukasi interaktif, serta dashboard manajemen data pasien dan jadwal konsultasi yang terintegrasi.",
    impact:
      "Helped shape a multi-feature mental health prototype with consultation, community, education, and dashboard flows for an academic team project.",
    highlights: [
      "Developed responsive React interfaces with Tailwind CSS.",
      "Connected frontend screens to Node.js, Express, and database-backed flows.",
      "Collaborated on user-facing product flows and prototype presentation.",
    ],
    year: "2024",
    status: "Prototype",
    tech: [
      tech("react", "React.js", SiReact, "#61DAFB"),
      tech("tailwindcss", "Tailwind CSS", SiTailwindcss, "#06B6D4"),
      tech("javascript", "JavaScript", SiJavascript, "#F7DF1E"),
      tech("nodejs", "Node.js", SiNodedotjs, "#339933"),
      tech("express", "Express.js", SiExpress, "#000000", "#ffffff"),
      tech("mysql", "MySQL", SiMysql, "#4479A1"),
      tech("sequelize", "Sequelize", SiSequelize, "#52B0E7"),
      tech("axios", "Axios", SiAxios, "#5A29E4"),
      tech("react-router", "React Router", SiReactrouter, "#CA4245"),
      tech("npm", "NPM", SiNpm, "#CB3837"),
      tech("apache", "Apache", SiApache, "#D62D20"),
      tech("mongodb", "MongoDB", SiMongodb, "#47A248"),
      tech("git", "Git", SiGit, "#F05032"),
      tech("github", "GitHub", SiGithub, "#181717", "#e6edf3"),
      tech("github-actions", "GitHub Actions", SiGithubactions, "#2088FF"),
    ],
    links: [
      projectLink(
        "frontend",
        "Frontend",
        "https://github.com/kupzed/InnerStrength-Full",
        "primary",
      ),
      projectLink(
        "backend",
        "Backend",
        "https://github.com/kupzed/InnerStrength-Full",
        "secondary",
      ),
    ],
    thumbnail: "/projects/innerstrength.png",
    bgColor: "#055777",
  },
  {
    id: "graphic-design-photography-portfolio",
    title: "Graphic Design & Photography Portfolio",
    role: "Graphic Designer and Photographer",
    type: "Creative work showcase",
    description:
      "A comprehensive showcase of creative works featuring graphic design, professional photography, and user interface design. This portfolio highlights expertise in social media design, branding, visual identification, and creative content creation.",
    impact:
      "Packaged visual design and photography work into a public creative portfolio that supports the broader product design story.",
    highlights: [
      "Produced social media visuals, branding assets, and publication materials.",
      "Edited photography and visual documentation for events and campaigns.",
      "Presented creative range through Behance and shared design files.",
    ],
    year: "2023",
    status: "Published",
    tech: [
      tech(
        "adobe-illustrator",
        "Adobe Illustrator",
        SiAdobeillustrator,
        "#FF9A00",
      ),
      tech("adobe-photoshop", "Adobe Photoshop", SiAdobephotoshop, "#31A8FF"),
      tech("adobe-lightroom", "Adobe Lightroom", SiAdobelightroom, "#31A8FF"),
      tech(
        "adobe-acrobat",
        "Adobe Acrobat XI Pro",
        SiAdobeacrobatreader,
        "#FF0000",
      ),
      tech("behance", "Behance", SiBehance, "#1769FF"),
    ],
    links: [
      projectLink(
        "behance",
        "Behance",
        "https://www.behance.net/gallery/186828953/Graphic-Design-and-Photography-Portfolio",
        "primary",
      ),
      projectLink(
        "files",
        "Files",
        "https://drive.google.com/file/d/1sYY7UXvSd7d_aamqVoAYvFtopnpI43ql/view?usp=sharing",
        "secondary",
      ),
    ],
    thumbnail: "/projects/graphic-design-portfolio.png",
    bgColor: "#0b3a22",
  },
  {
    id: "go-travel",
    title: "Go Travel",
    role: "UI/UX Designer",
    type: "Travel booking mobile prototype",
    description:
      "A comprehensive UI/UX mockup for an open and private trip application focused on nature tourism. Designed to simplify travel planning, the prototype features intuitive destination discovery, quick reviews, an integrated booking and payment system, as well as real-time messaging. The interface was carefully crafted to ensure a seamless and engaging user experience for travelers.",
    impact:
      "Designed a complete travel booking prototype that turns destination discovery, reviews, booking, payment, and messaging into one guided flow.",
    highlights: [
      "Mapped discovery-to-booking user journeys for nature tourism.",
      "Designed high-fidelity Figma screens and interactive prototype states.",
      "Focused on quick scanning, trust, and booking clarity.",
    ],
    year: "2024",
    status: "Prototype",
    tech: [tech("figma", "Figma", SiFigma, "#F24E1E")],
    links: [
      projectLink(
        "prototype",
        "Prototype",
        "https://www.figma.com/proto/Hn9TuKyPPGrfJ3WKZ8o5Zr/Go-Travel?node-id=34-11409&p=f&t=MUXUc93hgzurvwQP-1&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=34%3A8998",
        "primary",
      ),
      projectLink(
        "design",
        "Design",
        "https://www.figma.com/design/Hn9TuKyPPGrfJ3WKZ8o5Zr/Go-Travel?node-id=0-1&t=PAR1i2kolXYbRXig-1",
        "secondary",
      ),
    ],
    thumbnail: "/projects/gotravel.png",
    bgColor: "#bc3f00",
  },
  {
    id: "pencatatan-keuangan",
    title: "Pencatatan Keuangan",
    role: "UI/UX Designer",
    type: "Personal finance mobile prototype",
    description:
      "A comprehensive UI/UX design for an Android-based personal financial tracking application. Developed using the Design Thinking methodology, this project focuses on creating an intuitive and user-friendly mobile experience to help users effortlessly record, monitor, and manage their daily income and expenses.",
    impact:
      "Designed a mobile-first finance tracking concept that helps users record, monitor, and understand daily income and expense activity.",
    highlights: [
      "Used Design Thinking to shape the recording and monitoring workflow.",
      "Created a Figma prototype for daily personal finance actions.",
      "Prioritized simple entry, readable summaries, and mobile usability.",
    ],
    year: "2024",
    status: "Prototype",
    tech: [tech("figma", "Figma", SiFigma, "#F24E1E")],
    links: [
      projectLink(
        "prototype",
        "Prototype",
        "https://www.figma.com/proto/X7wjaJqbbG5x1nvxMOfcbA/Pencatatan-Keuangan?node-id=34-11409&p=f&t=MUXUc93hgzurvwQP-1&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=34%3A8998",
        "primary",
      ),
      projectLink(
        "design",
        "Design",
        "https://www.figma.com/design/X7wjaJqbbG5x1nvxMOfcbA/Pencatatan-Keuangan?t=PAR1i2kolXYbRXig-1",
        "secondary",
      ),
    ],
    thumbnail: "/projects/pencatatan-keuangan.png",
    bgColor: "#00631c",
  },
];
