import { FileCode2 } from "lucide-react";
import {
  SiAdobeacrobatreader,
  SiAdobeaftereffects,
  SiAdobeaudition,
  SiAdobeillustrator,
  SiAdobelightroom,
  SiAdobephotoshop,
  SiAdobepremierepro,
  SiAnthropic,
  SiApache,
  SiAxios,
  SiBehance,
  SiBootstrap,
  SiCanva,
  SiCoreldraw,
  SiCss3,
  SiDocker,
  SiExpress,
  SiFigma,
  SiFirebase,
  SiFramer,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGo,
  SiGooglegemini,
  SiHtml5,
  SiJavascript,
  SiJsonwebtokens,
  SiLaravel,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiNpm,
  SiOpenai,
  SiPhp,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPython,
  SiReact,
  SiReactrouter,
  SiSequelize,
  SiSolidity,
  SiSqlite,
  SiSupabase,
  SiSvelte,
  SiTailwindcss,
  SiTypescript,
  SiUbuntu,
  SiVercel,
  SiVite,
  SiWeb3Dotjs,
  SiWordpress,
} from "react-icons/si";
import type { Skill, SkillTab } from "@/lib/types";

export const SKILL_TABS = [
  "Frontend",
  "Backend",
  "Tech",
  "Design",
] as const satisfies readonly SkillTab[];

export const skillsByTab: Record<SkillTab, Skill[]> = {
  Frontend: [
    { id: "html5", name: "HTML5", icon: SiHtml5, color: "#E34F26" },
    { id: "css3", name: "CSS3", icon: SiCss3, color: "#1572B6" },
    { id: "javascript", name: "JavaScript", icon: SiJavascript, color: "#F7DF1E" },
    { id: "typescript", name: "TypeScript", icon: SiTypescript, color: "#3178C6" },
    { id: "bootstrap", name: "Bootstrap", icon: SiBootstrap, color: "#7952B3" },
    { id: "react", name: "ReactJS", icon: SiReact, color: "#61DAFB" },
    {
      id: "nextjs",
      name: "Next.js",
      icon: SiNextdotjs,
      color: "#000000",
      darkColor: "#ffffff",
    },
    { id: "sveltekit", name: "SvelteKit", icon: SiSvelte, color: "#FF3E00" },
    { id: "tailwindcss", name: "TailwindCSS", icon: SiTailwindcss, color: "#06B6D4" },
    { id: "framer", name: "Framer", icon: SiFramer, color: "#0055FF" },
    { id: "react-router", name: "React Router", icon: SiReactrouter, color: "#CA4245" },
    { id: "axios", name: "Axios", icon: SiAxios, color: "#5A29E4" },
  ],
  Backend: [
    { id: "php", name: "PHP", icon: SiPhp, color: "#777BB4" },
    { id: "laravel", name: "Laravel", icon: SiLaravel, color: "#FF2D20" },
    { id: "python", name: "Python", icon: SiPython, color: "#3776AB" },
    { id: "nodejs", name: "Node.js", icon: SiNodedotjs, color: "#5FA04E" },
    { id: "golang", name: "Golang", icon: SiGo, color: "#00ADD8" },
    { id: "java", name: "Java", icon: FileCode2, color: "#ED8B00" },
    { id: "mysql", name: "MySQL", icon: SiMysql, color: "#4479A1" },
    { id: "mongodb", name: "MongoDB", icon: SiMongodb, color: "#47A248" },
    { id: "sqlite", name: "SQLite", icon: SiSqlite, color: "#003B57" },
    { id: "firebase", name: "Firebase", icon: SiFirebase, color: "#DD2C00" },
    { id: "supabase", name: "Supabase", icon: SiSupabase, color: "#3ECF8E" },
    { id: "prisma", name: "Prisma", icon: SiPrisma, color: "#3178C6" },
    { id: "sequelize", name: "Sequelize", icon: SiSequelize, color: "#01AFEF" },
    { id: "postgresql", name: "PostgreSQL", icon: SiPostgresql, color: "#306095" },
    {
      id: "express",
      name: "Express.js",
      icon: SiExpress,
      color: "#000000",
      darkColor: "#ffffff",
    },
    {
      id: "jwt",
      name: "JWT",
      icon: SiJsonwebtokens,
      color: "#000000",
      darkColor: "#ffffff",
    },
  ],
  Tech: [
    { id: "vite", name: "Vite", icon: SiVite, color: "#646CFF" },
    { id: "npm", name: "NPM", icon: SiNpm, color: "#CB3837" },
    { id: "postman", name: "Postman", icon: SiPostman, color: "#FF6C37" },
    { id: "vercel", name: "Vercel", icon: SiVercel, color: "#000000", darkColor: "#ffffff" },
    { id: "apache", name: "Apache", icon: SiApache, color: "#D22128" },
    { id: "wordpress", name: "WordPress", icon: SiWordpress, color: "#21759B" },
    { id: "framer-tech", name: "Framer", icon: SiFramer, color: "#0055FF" },
    { id: "git", name: "Git", icon: SiGit, color: "#F05032" },
    { id: "github", name: "GitHub", icon: SiGithub, color: "#181717", darkColor: "#e6edf3" },
    { id: "github-actions", name: "GitHub Actions", icon: SiGithubactions, color: "#2088FF" },
    { id: "linux", name: "Linux", icon: SiLinux, color: "#FCC624" },
    { id: "ubuntu", name: "Ubuntu", icon: SiUbuntu, color: "#E95420" },
    { id: "docker", name: "Docker", icon: SiDocker, color: "#000000", darkColor: "#ffffff" },
    { id: "smart-contracts", name: "Smart Contracts", icon: FileCode2, color: "#8B5CF6" },
    { id: "web3", name: "Web3", icon: SiWeb3Dotjs, color: "#F16822" },
    { id: "solidity", name: "Solidity", icon: SiSolidity, color: "#000000", darkColor: "#ffffff" },
    { id: "anthropic", name: "Anthropic", icon: SiAnthropic, color: "#000000", darkColor: "#ffffff" },
    { id: "google-gemini", name: "Google Gemini", icon: SiGooglegemini, color: "#000000", darkColor: "#ffffff" },
    { id: "openai", name: "OpenAI", icon: SiOpenai, color: "#000000", darkColor: "#ffffff" },
  ],
  Design: [
    { id: "adobe-illustrator", name: "Adobe Illustrator", icon: SiAdobeillustrator, color: "#FF9A00" },
    { id: "adobe-photoshop", name: "Adobe Photoshop", icon: SiAdobephotoshop, color: "#00A1EF" },
    { id: "adobe-lightroom", name: "Adobe Lightroom", icon: SiAdobelightroom, color: "#31A8FF" },
    { id: "adobe-premiere-pro", name: "Adobe Premiere Pro", icon: SiAdobepremierepro, color: "#9999FF" },
    { id: "adobe-after-effects", name: "Adobe After Effects", icon: SiAdobeaftereffects, color: "#9999FF" },
    { id: "adobe-audition", name: "Adobe Audition", icon: SiAdobeaudition, color: "#00E4B5" },
    { id: "adobe-acrobat", name: "Adobe Acrobat XI Pro", icon: SiAdobeacrobatreader, color: "#FF0000" },
    { id: "coreldraw", name: "CorelDRAW", icon: SiCoreldraw, color: "#000000", darkColor: "#ffffff" },
    { id: "canva", name: "Canva", icon: SiCanva, color: "#00C4CC" },
    { id: "figma", name: "Figma", icon: SiFigma, color: "#F24E1E" },
    { id: "behance", name: "Behance", icon: SiBehance, color: "#1769FF" },
  ],
};

export const allSkills = Object.values(skillsByTab).flat();
